# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avatar.ui'
#
# Created: Sat Jan 04 20:07:09 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AvatarWindow(object):
    def setupUi(self, AvatarWindow):
        AvatarWindow.setObjectName(_fromUtf8("AvatarWindow"))
        AvatarWindow.resize(458, 475)
        AvatarWindow.setWindowTitle(QtGui.QApplication.translate("AvatarWindow", "Discuz 自定义头像工具", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(AvatarWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupAccount = QtGui.QGroupBox(self.centralwidget)
        self.groupAccount.setTitle(QtGui.QApplication.translate("AvatarWindow", "登录帐号", None, QtGui.QApplication.UnicodeUTF8))
        self.groupAccount.setObjectName(_fromUtf8("groupAccount"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupAccount)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblUser = QtGui.QLabel(self.groupAccount)
        self.lblUser.setText(QtGui.QApplication.translate("AvatarWindow", "用户", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUser.setObjectName(_fromUtf8("lblUser"))
        self.horizontalLayout_5.addWidget(self.lblUser)
        self.txtUser = QtGui.QLineEdit(self.groupAccount)
        self.txtUser.setObjectName(_fromUtf8("txtUser"))
        self.horizontalLayout_5.addWidget(self.txtUser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblPass = QtGui.QLabel(self.groupAccount)
        self.lblPass.setText(QtGui.QApplication.translate("AvatarWindow", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPass.setObjectName(_fromUtf8("lblPass"))
        self.horizontalLayout_6.addWidget(self.lblPass)
        self.txtPass = QtGui.QLineEdit(self.groupAccount)
        self.txtPass.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPass.setObjectName(_fromUtf8("txtPass"))
        self.horizontalLayout_6.addWidget(self.txtPass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblQues = QtGui.QLabel(self.groupAccount)
        self.lblQues.setMinimumSize(QtCore.QSize(24, 0))
        self.lblQues.setMaximumSize(QtCore.QSize(24, 16777215))
        self.lblQues.setText(QtGui.QApplication.translate("AvatarWindow", "问题", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQues.setObjectName(_fromUtf8("lblQues"))
        self.horizontalLayout_7.addWidget(self.lblQues)
        self.txtQues = QtGui.QComboBox(self.groupAccount)
        self.txtQues.setObjectName(_fromUtf8("txtQues"))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(0, QtGui.QApplication.translate("AvatarWindow", "安全提问(未设置请忽略)", "0", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(1, QtGui.QApplication.translate("AvatarWindow", "母亲的名字", "1", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(2, QtGui.QApplication.translate("AvatarWindow", "爷爷的名字", "2", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(3, QtGui.QApplication.translate("AvatarWindow", "父亲出生的城市", "3", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(4, QtGui.QApplication.translate("AvatarWindow", "你其中一位老师的名字", "4", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(5, QtGui.QApplication.translate("AvatarWindow", "你个人计算机的型号", "5", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(6, QtGui.QApplication.translate("AvatarWindow", "你最喜欢的餐馆名称", "6", QtGui.QApplication.UnicodeUTF8))
        self.txtQues.addItem(_fromUtf8(""))
        self.txtQues.setItemText(7, QtGui.QApplication.translate("AvatarWindow", "驾驶执照最后四位数字", "7", QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_7.addWidget(self.txtQues)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblAnsw = QtGui.QLabel(self.groupAccount)
        self.lblAnsw.setText(QtGui.QApplication.translate("AvatarWindow", "答案", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAnsw.setObjectName(_fromUtf8("lblAnsw"))
        self.horizontalLayout_8.addWidget(self.lblAnsw)
        self.txtAnsw = QtGui.QLineEdit(self.groupAccount)
        self.txtAnsw.setObjectName(_fromUtf8("txtAnsw"))
        self.horizontalLayout_8.addWidget(self.txtAnsw)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupAccount)
        self.groupAvatars = QtGui.QGroupBox(self.centralwidget)
        self.groupAvatars.setTitle(QtGui.QApplication.translate("AvatarWindow", "头像文件", None, QtGui.QApplication.UnicodeUTF8))
        self.groupAvatars.setObjectName(_fromUtf8("groupAvatars"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupAvatars)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblAvatar1 = QtGui.QLabel(self.groupAvatars)
        self.lblAvatar1.setText(QtGui.QApplication.translate("AvatarWindow", "大头像", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAvatar1.setObjectName(_fromUtf8("lblAvatar1"))
        self.horizontalLayout_2.addWidget(self.lblAvatar1)
        self.txtAvatar1 = QtGui.QLineEdit(self.groupAvatars)
        self.txtAvatar1.setObjectName(_fromUtf8("txtAvatar1"))
        self.horizontalLayout_2.addWidget(self.txtAvatar1)
        self.btnBrowse1 = QtGui.QToolButton(self.groupAvatars)
        self.btnBrowse1.setText(QtGui.QApplication.translate("AvatarWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse1.setObjectName(_fromUtf8("btnBrowse1"))
        self.horizontalLayout_2.addWidget(self.btnBrowse1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblAvatar2 = QtGui.QLabel(self.groupAvatars)
        self.lblAvatar2.setText(QtGui.QApplication.translate("AvatarWindow", "中头像", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAvatar2.setObjectName(_fromUtf8("lblAvatar2"))
        self.horizontalLayout_3.addWidget(self.lblAvatar2)
        self.txtAvatar2 = QtGui.QLineEdit(self.groupAvatars)
        self.txtAvatar2.setObjectName(_fromUtf8("txtAvatar2"))
        self.horizontalLayout_3.addWidget(self.txtAvatar2)
        self.btnBrowse2 = QtGui.QToolButton(self.groupAvatars)
        self.btnBrowse2.setText(QtGui.QApplication.translate("AvatarWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse2.setObjectName(_fromUtf8("btnBrowse2"))
        self.horizontalLayout_3.addWidget(self.btnBrowse2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblAvatar3 = QtGui.QLabel(self.groupAvatars)
        self.lblAvatar3.setText(QtGui.QApplication.translate("AvatarWindow", "小头像", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAvatar3.setObjectName(_fromUtf8("lblAvatar3"))
        self.horizontalLayout_4.addWidget(self.lblAvatar3)
        self.txtAvatar3 = QtGui.QLineEdit(self.groupAvatars)
        self.txtAvatar3.setObjectName(_fromUtf8("txtAvatar3"))
        self.horizontalLayout_4.addWidget(self.txtAvatar3)
        self.btnBrowse3 = QtGui.QToolButton(self.groupAvatars)
        self.btnBrowse3.setText(QtGui.QApplication.translate("AvatarWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse3.setObjectName(_fromUtf8("btnBrowse3"))
        self.horizontalLayout_4.addWidget(self.btnBrowse3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupAvatars)
        self.groupStatus = QtGui.QGroupBox(self.centralwidget)
        self.groupStatus.setTitle(QtGui.QApplication.translate("AvatarWindow", "状态", None, QtGui.QApplication.UnicodeUTF8))
        self.groupStatus.setObjectName(_fromUtf8("groupStatus"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupStatus)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.txtStatus = QtGui.QPlainTextEdit(self.groupStatus)
        self.txtStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtStatus.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.txtStatus.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.txtStatus.setReadOnly(True)
        self.txtStatus.setObjectName(_fromUtf8("txtStatus"))
        self.verticalLayout_4.addWidget(self.txtStatus)
        self.verticalLayout.addWidget(self.groupStatus)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnUpload = QtGui.QPushButton(self.centralwidget)
        self.btnUpload.setText(QtGui.QApplication.translate("AvatarWindow", "上传", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpload.setObjectName(_fromUtf8("btnUpload"))
        self.horizontalLayout.addWidget(self.btnUpload)
        self.btnExit = QtGui.QPushButton(self.centralwidget)
        self.btnExit.setText(QtGui.QApplication.translate("AvatarWindow", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout.addWidget(self.btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        AvatarWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AvatarWindow)
        QtCore.QObject.connect(self.btnExit, QtCore.SIGNAL(_fromUtf8("clicked()")), AvatarWindow.close)
        QtCore.QObject.connect(AvatarWindow, QtCore.SIGNAL(_fromUtf8("destroyed()")), AvatarWindow.exitTriggered)
        QtCore.QObject.connect(self.btnUpload, QtCore.SIGNAL(_fromUtf8("clicked()")), AvatarWindow.uploadSumit)
        QtCore.QObject.connect(self.btnBrowse1, QtCore.SIGNAL(_fromUtf8("clicked()")), AvatarWindow.changeAvatar1)
        QtCore.QObject.connect(self.btnBrowse2, QtCore.SIGNAL(_fromUtf8("clicked()")), AvatarWindow.changeAvatar2)
        QtCore.QObject.connect(self.btnBrowse3, QtCore.SIGNAL(_fromUtf8("clicked()")), AvatarWindow.changeAvatar3)
        QtCore.QMetaObject.connectSlotsByName(AvatarWindow)
        AvatarWindow.setTabOrder(self.txtUser, self.txtPass)
        AvatarWindow.setTabOrder(self.txtPass, self.txtAnsw)
        AvatarWindow.setTabOrder(self.txtAnsw, self.txtAvatar1)
        AvatarWindow.setTabOrder(self.txtAvatar1, self.txtAvatar2)
        AvatarWindow.setTabOrder(self.txtAvatar2, self.txtAvatar3)
        AvatarWindow.setTabOrder(self.txtAvatar3, self.btnBrowse1)
        AvatarWindow.setTabOrder(self.btnBrowse1, self.btnBrowse2)
        AvatarWindow.setTabOrder(self.btnBrowse2, self.btnBrowse3)
        AvatarWindow.setTabOrder(self.btnBrowse3, self.txtStatus)
        AvatarWindow.setTabOrder(self.txtStatus, self.btnUpload)
        AvatarWindow.setTabOrder(self.btnUpload, self.btnExit)

    def retranslateUi(self, AvatarWindow):
        pass

